### ISSUE TITLE
Unable to find Arma 3 installed on C: drive

### ISSUE THREAD

**Issue by Pr0phet-of-Fear** [thomotron/arma-3-workshop-cleaner#1]
`find_arma_workshop_dir()` is unable to find Arma 3 installed on my C: drive, as that library is not listed in libraryfolders.vdf. Only my steam libraries on other drives are listed there.

**Comment by thomotron** [comment]
Looks like I missed the critical detail of `libraryfolders.vdf` not containing the default library...
So Arma is installed under `C:\Program Files (x86)\Steam\steamapps\common\Arma 3\`?

**Comment by Pr0phet-of-Fear** [comment]
Correct.

**Comment by thomotron** [comment]
Give that one a test. It should check the default location first.

**Comment by Pr0phet-of-Fear** [comment]
![image](https://user-images.githubusercontent.com/49212464/103722123-46219d80-4f9d-11eb-93b2-732809fd56ae.png)

**Comment by Pr0phet-of-Fear** [comment]
So, it looks like the issue I was having was fixed, but there's a new one.
